server:
  port: 8081

spring:
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
  application:
    name: product
  data:
    mongodb:
      uri: mongodb+srv://pacherresfloresjose12:pMUdDip0xRP4kiZy@cluster0.5gmvqd9.mongodb.net/dbbank

webclient:
  base-url-customer: http://localhost:8080

springdoc:
  swagger-ui:
    path: index.html


bank:
  accounts:
    savings:
      maintenanceFee: false
      maxMonthlyTransactions: 10
    current:
      maintenanceFee: true
      maxMonthlyTransactions: -1 
    fixedDeposit:
      maintenanceFee: false
      maxMonthlyTransactions: 1
      specificTransactionDay: 15 
  credits:
    personal:
      maxCreditsPerPerson: 1
    business:
      maxCreditsPerCompany: -1 
    creditCard:
      personal:
        allowed: true
      business:
        allowed: true
